[2025-04-10T11:16:22.854+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-10T11:16:22.865+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lstm_stock_prediction_refactored.build_features manual__2025-04-10T11:13:41.242366+00:00 [queued]>
[2025-04-10T11:16:22.871+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lstm_stock_prediction_refactored.build_features manual__2025-04-10T11:13:41.242366+00:00 [queued]>
[2025-04-10T11:16:22.872+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-10T11:16:22.880+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): build_features> on 2025-04-10 11:13:41.242366+00:00
[2025-04-10T11:16:22.884+0000] {standard_task_runner.py:72} INFO - Started process 2733 to run task
[2025-04-10T11:16:22.887+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'lstm_stock_prediction_refactored', 'build_features', 'manual__2025-04-10T11:13:41.242366+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/lstm_refactored_dag.py', '--cfg-path', '/tmp/tmpo92xm777']
[2025-04-10T11:16:22.888+0000] {standard_task_runner.py:105} INFO - Job 53: Subtask build_features
[2025-04-10T11:16:22.918+0000] {task_command.py:467} INFO - Running <TaskInstance: lstm_stock_prediction_refactored.build_features manual__2025-04-10T11:13:41.242366+00:00 [running]> on host f4de05ccd019
[2025-04-10T11:16:22.964+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***_team' AIRFLOW_CTX_DAG_ID='lstm_stock_prediction_refactored' AIRFLOW_CTX_TASK_ID='build_features' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T11:13:41.242366+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-10T11:13:41.242366+00:00'
[2025-04-10T11:16:22.971+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-10T11:16:22.998+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-10T11:16:23.005+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/src/features/build_features.py --config /opt/***/config/params.yaml']
[2025-04-10T11:16:23.017+0000] {subprocess.py:99} INFO - Output:
[2025-04-10T11:16:23.910+0000] {subprocess.py:106} INFO - --- Loading Processed Data from data/processed/all_processed_data.npz ---
[2025-04-10T11:16:23.911+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-04-10T11:16:23.911+0000] {subprocess.py:106} INFO -   File "/opt/***/src/features/build_features.py", line 146, in <module>
[2025-04-10T11:16:23.912+0000] {subprocess.py:106} INFO -     run_feature_building(args.config)
[2025-04-10T11:16:23.912+0000] {subprocess.py:106} INFO -   File "/opt/***/src/features/build_features.py", line 90, in run_feature_building
[2025-04-10T11:16:23.914+0000] {subprocess.py:106} INFO -     data = np.load(processed_data_path, allow_pickle=True)
[2025-04-10T11:16:23.915+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-10T11:16:23.915+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.11/site-packages/numpy/lib/npyio.py", line 427, in load
[2025-04-10T11:16:23.916+0000] {subprocess.py:106} INFO -     fid = stack.enter_context(open(os_fspath(file), "rb"))
[2025-04-10T11:16:23.916+0000] {subprocess.py:106} INFO -                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-10T11:16:23.916+0000] {subprocess.py:106} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/all_processed_data.npz'
[2025-04-10T11:16:23.970+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-10T11:16:23.978+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-10T11:16:23.983+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=lstm_stock_prediction_refactored, task_id=build_features, run_id=manual__2025-04-10T11:13:41.242366+00:00, execution_date=20250410T111341, start_date=20250410T111622, end_date=20250410T111623
[2025-04-10T11:16:23.999+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-10T11:16:24.001+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 53 for task build_features (Bash command failed. The command returned a non-zero exit code 1.; 2733)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-10T11:16:24.023+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-10T11:16:24.039+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-10T11:16:24.042+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
