[2025-04-21T17:32:37.493+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-21T17:32:37.582+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lstm_stock_prediction_refactored.generate_predictions scheduled__2025-04-14T08:00:00+00:00 [queued]>
[2025-04-21T17:32:37.601+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lstm_stock_prediction_refactored.generate_predictions scheduled__2025-04-14T08:00:00+00:00 [queued]>
[2025-04-21T17:32:37.602+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-21T17:32:37.632+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): generate_predictions> on 2025-04-14 08:00:00+00:00
[2025-04-21T17:32:37.648+0000] {standard_task_runner.py:72} INFO - Started process 943 to run task
[2025-04-21T17:32:37.654+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'lstm_stock_prediction_refactored', 'generate_predictions', 'scheduled__2025-04-14T08:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/lstm_refactored_dag.py', '--cfg-path', '/tmp/tmphlkkz04c']
[2025-04-21T17:32:37.665+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask generate_predictions
[2025-04-21T17:32:37.861+0000] {task_command.py:467} INFO - Running <TaskInstance: lstm_stock_prediction_refactored.generate_predictions scheduled__2025-04-14T08:00:00+00:00 [running]> on host a528bcf7a8c9
[2025-04-21T17:32:38.112+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***_team' AIRFLOW_CTX_DAG_ID='lstm_stock_prediction_refactored' AIRFLOW_CTX_TASK_ID='generate_predictions' AIRFLOW_CTX_EXECUTION_DATE='2025-04-14T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-14T08:00:00+00:00'
[2025-04-21T17:32:38.117+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-21T17:32:38.225+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-21T17:32:38.239+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/src/models/predict_model.py --config /opt/***/config/params.yaml']
[2025-04-21T17:32:38.255+0000] {subprocess.py:99} INFO - Output:
[2025-04-21T17:32:51.746+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-04-21T17:32:51.760+0000] {subprocess.py:106} INFO -   File "/opt/***/src/models/predict_model.py", line 132, in <module>
[2025-04-21T17:32:51.763+0000] {subprocess.py:106} INFO -     if __name__ == '__main__':
[2025-04-21T17:32:51.765+0000] {subprocess.py:106} INFO -        ^^^^^^
[2025-04-21T17:32:51.766+0000] {subprocess.py:106} INFO - NameError: name '_name_' is not defined. Did you mean: '__name__'?
[2025-04-21T17:32:53.209+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-21T17:32:53.293+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-21T17:32:53.311+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=lstm_stock_prediction_refactored, task_id=generate_predictions, run_id=scheduled__2025-04-14T08:00:00+00:00, execution_date=20250414T080000, start_date=20250421T173237, end_date=20250421T173253
[2025-04-21T17:32:53.372+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-21T17:32:53.375+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 14 for task generate_predictions (Bash command failed. The command returned a non-zero exit code 1.; 943)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-21T17:32:53.412+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-21T17:32:53.456+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-21T17:32:53.459+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
