[2025-04-10T10:33:21.379+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-10T10:33:21.391+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lstm_stock_prediction_refactored.build_features scheduled__2025-03-31T08:00:00+00:00 [queued]>
[2025-04-10T10:33:21.396+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lstm_stock_prediction_refactored.build_features scheduled__2025-03-31T08:00:00+00:00 [queued]>
[2025-04-10T10:33:21.397+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-10T10:33:21.404+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): build_features> on 2025-03-31 08:00:00+00:00
[2025-04-10T10:33:21.411+0000] {standard_task_runner.py:72} INFO - Started process 1814 to run task
[2025-04-10T10:33:21.413+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'lstm_stock_prediction_refactored', 'build_features', 'scheduled__2025-03-31T08:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/lstm_refactored_dag.py', '--cfg-path', '/tmp/tmpagctwu3k']
[2025-04-10T10:33:21.415+0000] {standard_task_runner.py:105} INFO - Job 49: Subtask build_features
[2025-04-10T10:33:21.454+0000] {task_command.py:467} INFO - Running <TaskInstance: lstm_stock_prediction_refactored.build_features scheduled__2025-03-31T08:00:00+00:00 [running]> on host f4de05ccd019
[2025-04-10T10:33:21.520+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***_team' AIRFLOW_CTX_DAG_ID='lstm_stock_prediction_refactored' AIRFLOW_CTX_TASK_ID='build_features' AIRFLOW_CTX_EXECUTION_DATE='2025-03-31T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-31T08:00:00+00:00'
[2025-04-10T10:33:21.521+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-10T10:33:21.531+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-10T10:33:21.532+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/src/features/build_features.py --config /opt/***/config/params.yaml']
[2025-04-10T10:33:21.539+0000] {subprocess.py:99} INFO - Output:
[2025-04-10T10:33:22.125+0000] {subprocess.py:106} INFO - --- Loading Processed Data from data/processed/all_processed_data.npz ---
[2025-04-10T10:33:22.126+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-04-10T10:33:22.126+0000] {subprocess.py:106} INFO -   File "/opt/***/src/features/build_features.py", line 146, in <module>
[2025-04-10T10:33:22.127+0000] {subprocess.py:106} INFO -     run_feature_building(args.config)
[2025-04-10T10:33:22.127+0000] {subprocess.py:106} INFO -   File "/opt/***/src/features/build_features.py", line 90, in run_feature_building
[2025-04-10T10:33:22.127+0000] {subprocess.py:106} INFO -     data = np.load(processed_data_path, allow_pickle=True)
[2025-04-10T10:33:22.128+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-10T10:33:22.128+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.11/site-packages/numpy/lib/npyio.py", line 427, in load
[2025-04-10T10:33:22.128+0000] {subprocess.py:106} INFO -     fid = stack.enter_context(open(os_fspath(file), "rb"))
[2025-04-10T10:33:22.128+0000] {subprocess.py:106} INFO -                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-10T10:33:22.129+0000] {subprocess.py:106} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/all_processed_data.npz'
[2025-04-10T10:33:22.177+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-10T10:33:22.185+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-10T10:33:22.190+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=lstm_stock_prediction_refactored, task_id=build_features, run_id=scheduled__2025-03-31T08:00:00+00:00, execution_date=20250331T080000, start_date=20250410T103321, end_date=20250410T103322
[2025-04-10T10:33:22.209+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-10T10:33:22.211+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 49 for task build_features (Bash command failed. The command returned a non-zero exit code 1.; 1814)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-10T10:33:22.227+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-10T10:33:22.234+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-11T05:44:30.257+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-11T05:44:30.296+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lstm_stock_prediction_refactored.build_features scheduled__2025-03-31T08:00:00+00:00 [queued]>
[2025-04-11T05:44:30.310+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lstm_stock_prediction_refactored.build_features scheduled__2025-03-31T08:00:00+00:00 [queued]>
[2025-04-11T05:44:30.311+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-11T05:44:30.336+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): build_features> on 2025-03-31 08:00:00+00:00
[2025-04-11T05:44:30.341+0000] {standard_task_runner.py:72} INFO - Started process 277 to run task
[2025-04-11T05:44:30.343+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'lstm_stock_prediction_refactored', 'build_features', 'scheduled__2025-03-31T08:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/lstm_refactored_dag.py', '--cfg-path', '/tmp/tmp7izfgbiu']
[2025-04-11T05:44:30.346+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask build_features
[2025-04-11T05:44:30.452+0000] {task_command.py:467} INFO - Running <TaskInstance: lstm_stock_prediction_refactored.build_features scheduled__2025-03-31T08:00:00+00:00 [running]> on host 162c7a94827e
[2025-04-11T05:44:30.627+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***_team' AIRFLOW_CTX_DAG_ID='lstm_stock_prediction_refactored' AIRFLOW_CTX_TASK_ID='build_features' AIRFLOW_CTX_EXECUTION_DATE='2025-03-31T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-31T08:00:00+00:00'
[2025-04-11T05:44:30.628+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-11T05:44:30.650+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-11T05:44:30.652+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/src/features/build_features.py --config /opt/***/config/params.yaml']
[2025-04-11T05:44:30.665+0000] {subprocess.py:99} INFO - Output:
[2025-04-11T05:44:32.976+0000] {subprocess.py:106} INFO - --- Loading Processed Data from data/processed/all_processed_data.npz ---
[2025-04-11T05:44:32.977+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-04-11T05:44:32.978+0000] {subprocess.py:106} INFO -   File "/opt/***/src/features/build_features.py", line 146, in <module>
[2025-04-11T05:44:32.983+0000] {subprocess.py:106} INFO -     run_feature_building(args.config)
[2025-04-11T05:44:32.984+0000] {subprocess.py:106} INFO -   File "/opt/***/src/features/build_features.py", line 90, in run_feature_building
[2025-04-11T05:44:32.986+0000] {subprocess.py:106} INFO -     data = np.load(processed_data_path, allow_pickle=True)
[2025-04-11T05:44:32.987+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-11T05:44:32.987+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.11/site-packages/numpy/lib/_npyio_impl.py", line 451, in load
[2025-04-11T05:44:32.988+0000] {subprocess.py:106} INFO -     fid = stack.enter_context(open(os.fspath(file), "rb"))
[2025-04-11T05:44:32.989+0000] {subprocess.py:106} INFO -                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-11T05:44:32.990+0000] {subprocess.py:106} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/all_processed_data.npz'
[2025-04-11T05:44:33.450+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-11T05:44:33.461+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-11T05:44:33.470+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=lstm_stock_prediction_refactored, task_id=build_features, run_id=scheduled__2025-03-31T08:00:00+00:00, execution_date=20250331T080000, start_date=20250411T054430, end_date=20250411T054433
[2025-04-11T05:44:33.526+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-11T05:44:33.527+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task build_features (Bash command failed. The command returned a non-zero exit code 1.; 277)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-11T05:44:33.544+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-11T05:44:33.580+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-11T05:44:33.585+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
