[2025-04-10T10:35:23.222+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-10T10:35:23.233+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lstm_stock_prediction_refactored.build_features scheduled__2025-03-31T08:00:00+00:00 [queued]>
[2025-04-10T10:35:23.238+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lstm_stock_prediction_refactored.build_features scheduled__2025-03-31T08:00:00+00:00 [queued]>
[2025-04-10T10:35:23.239+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-10T10:35:23.247+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): build_features> on 2025-03-31 08:00:00+00:00
[2025-04-10T10:35:23.251+0000] {standard_task_runner.py:72} INFO - Started process 1892 to run task
[2025-04-10T10:35:23.253+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'lstm_stock_prediction_refactored', 'build_features', 'scheduled__2025-03-31T08:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/lstm_refactored_dag.py', '--cfg-path', '/tmp/tmpxqxsilo6']
[2025-04-10T10:35:23.255+0000] {standard_task_runner.py:105} INFO - Job 50: Subtask build_features
[2025-04-10T10:35:23.288+0000] {task_command.py:467} INFO - Running <TaskInstance: lstm_stock_prediction_refactored.build_features scheduled__2025-03-31T08:00:00+00:00 [running]> on host f4de05ccd019
[2025-04-10T10:35:23.335+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***_team' AIRFLOW_CTX_DAG_ID='lstm_stock_prediction_refactored' AIRFLOW_CTX_TASK_ID='build_features' AIRFLOW_CTX_EXECUTION_DATE='2025-03-31T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-31T08:00:00+00:00'
[2025-04-10T10:35:23.337+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-10T10:35:23.348+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-10T10:35:23.349+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/src/features/build_features.py --config /opt/***/config/params.yaml']
[2025-04-10T10:35:23.357+0000] {subprocess.py:99} INFO - Output:
[2025-04-10T10:35:23.952+0000] {subprocess.py:106} INFO - --- Loading Processed Data from data/processed/all_processed_data.npz ---
[2025-04-10T10:35:23.952+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-04-10T10:35:23.953+0000] {subprocess.py:106} INFO -   File "/opt/***/src/features/build_features.py", line 146, in <module>
[2025-04-10T10:35:23.953+0000] {subprocess.py:106} INFO -     run_feature_building(args.config)
[2025-04-10T10:35:23.954+0000] {subprocess.py:106} INFO -   File "/opt/***/src/features/build_features.py", line 90, in run_feature_building
[2025-04-10T10:35:23.954+0000] {subprocess.py:106} INFO -     data = np.load(processed_data_path, allow_pickle=True)
[2025-04-10T10:35:23.955+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-10T10:35:23.955+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.11/site-packages/numpy/lib/npyio.py", line 427, in load
[2025-04-10T10:35:23.956+0000] {subprocess.py:106} INFO -     fid = stack.enter_context(open(os_fspath(file), "rb"))
[2025-04-10T10:35:23.956+0000] {subprocess.py:106} INFO -                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-10T10:35:23.957+0000] {subprocess.py:106} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/all_processed_data.npz'
[2025-04-10T10:35:24.006+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-10T10:35:24.014+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-10T10:35:24.017+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=lstm_stock_prediction_refactored, task_id=build_features, run_id=scheduled__2025-03-31T08:00:00+00:00, execution_date=20250331T080000, start_date=20250410T103523, end_date=20250410T103524
[2025-04-10T10:35:24.032+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-10T10:35:24.033+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 50 for task build_features (Bash command failed. The command returned a non-zero exit code 1.; 1892)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-10T10:35:24.068+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-10T10:35:24.083+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-10T10:35:24.087+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
