[2025-04-11T09:41:25.666+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-11T09:41:25.684+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: lstm_stock_prediction_refactored.train_final_model manual__2025-04-11T09:38:46.502188+00:00 [queued]>
[2025-04-11T09:41:25.696+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: lstm_stock_prediction_refactored.train_final_model manual__2025-04-11T09:38:46.502188+00:00 [queued]>
[2025-04-11T09:41:25.701+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-11T09:41:25.714+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): train_final_model> on 2025-04-11 09:38:46.502188+00:00
[2025-04-11T09:41:25.719+0000] {standard_task_runner.py:72} INFO - Started process 457 to run task
[2025-04-11T09:41:25.722+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'lstm_stock_prediction_refactored', 'train_final_model', 'manual__2025-04-11T09:38:46.502188+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/lstm_refactored_dag.py', '--cfg-path', '/tmp/tmpd8vkqqoe']
[2025-04-11T09:41:25.726+0000] {standard_task_runner.py:105} INFO - Job 66: Subtask train_final_model
[2025-04-11T09:41:25.772+0000] {task_command.py:467} INFO - Running <TaskInstance: lstm_stock_prediction_refactored.train_final_model manual__2025-04-11T09:38:46.502188+00:00 [running]> on host 299156154de8
[2025-04-11T09:41:25.832+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***_team' AIRFLOW_CTX_DAG_ID='lstm_stock_prediction_refactored' AIRFLOW_CTX_TASK_ID='train_final_model' AIRFLOW_CTX_EXECUTION_DATE='2025-04-11T09:38:46.502188+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-11T09:38:46.502188+00:00'
[2025-04-11T09:41:25.834+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-11T09:41:25.845+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-11T09:41:25.846+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/src/models/train_model.py --config /opt/***/config/params.yaml']
[2025-04-11T09:41:25.856+0000] {subprocess.py:99} INFO - Output:
[2025-04-11T09:41:31.360+0000] {subprocess.py:106} INFO - 2025/04/11 09:41:31 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
[2025-04-11T09:41:31.361+0000] {subprocess.py:106} INFO - The git executable must be specified in one of the following ways:
[2025-04-11T09:41:31.362+0000] {subprocess.py:106} INFO -     - be included in your $PATH
[2025-04-11T09:41:31.363+0000] {subprocess.py:106} INFO -     - be set via $GIT_PYTHON_GIT_EXECUTABLE
[2025-04-11T09:41:31.364+0000] {subprocess.py:106} INFO -     - explicitly set via git.refresh(<full-path-to-git-executable>)
[2025-04-11T09:41:31.364+0000] {subprocess.py:106} INFO - 
[2025-04-11T09:41:31.365+0000] {subprocess.py:106} INFO - All git commands will error until this is rectified.
[2025-04-11T09:41:31.366+0000] {subprocess.py:106} INFO - 
[2025-04-11T09:41:31.366+0000] {subprocess.py:106} INFO - This initial message can be silenced or aggravated in the future by setting the
[2025-04-11T09:41:31.367+0000] {subprocess.py:106} INFO - $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
[2025-04-11T09:41:31.368+0000] {subprocess.py:106} INFO -     - quiet|q|silence|s|silent|none|n|0: for no message or exception
[2025-04-11T09:41:31.368+0000] {subprocess.py:106} INFO -     - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
[2025-04-11T09:41:31.369+0000] {subprocess.py:106} INFO -     - error|e|exception|raise|r|2: for a raised exception
[2025-04-11T09:41:31.370+0000] {subprocess.py:106} INFO - 
[2025-04-11T09:41:31.370+0000] {subprocess.py:106} INFO - Example:
[2025-04-11T09:41:31.371+0000] {subprocess.py:106} INFO -     export GIT_PYTHON_REFRESH=quiet
[2025-04-11T09:41:31.372+0000] {subprocess.py:106} INFO - 
[2025-04-11T09:41:40.240+0000] {subprocess.py:106} INFO - [31m2025/04/11 09:41:40 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.[0m
[2025-04-11T09:41:40.335+0000] {subprocess.py:106} INFO - Using device: cpu
[2025-04-11T09:41:40.337+0000] {subprocess.py:106} INFO - --- Loading Scaled Data from /opt/***/data/features/split_scaled_data.npz ---
[2025-04-11T09:41:40.339+0000] {subprocess.py:106} INFO - --- Finished Loading Scaled Data ---
[2025-04-11T09:41:40.344+0000] {subprocess.py:106} INFO - --- Loading Scalers from /opt/***/data/processed/scalers.pkl ---
[2025-04-11T09:41:40.350+0000] {subprocess.py:106} INFO - --- Finished Loading Scalers ---
[2025-04-11T09:41:40.354+0000] {subprocess.py:106} INFO - --- Loading Tickers from /opt/***/data/processed/all_processed_data.npz ---
[2025-04-11T09:41:40.362+0000] {subprocess.py:106} INFO - Tickers: ['AAPL', 'MA', 'CSCO', 'MSFT', 'AMZN', 'GOOG', 'IBM']
[2025-04-11T09:41:40.366+0000] {subprocess.py:106} INFO - --- Finished Loading Tickers ---
[2025-04-11T09:41:40.372+0000] {subprocess.py:106} INFO - --- Loading Best Hyperparameters from /opt/***/config/best_params.json ---
[2025-04-11T09:41:40.374+0000] {subprocess.py:106} INFO - Best parameters loaded: {'batch_size': 48, 'hidden_size': 224, 'num_layers': 3, 'dropout_rate': 0.5, 'learning_rate': 0.0052057929707301515, 'model_type': 'lstm'}
[2025-04-11T09:41:40.380+0000] {subprocess.py:106} INFO - --- Finished Loading Best Hyperparameters ---
[2025-04-11T09:41:40.384+0000] {subprocess.py:106} INFO - --- Setting MLflow Experiment: Stock_Price_Prediction_LSTM_Refactored ---
[2025-04-11T09:41:40.388+0000] {subprocess.py:106} INFO - Using MLflow Tracking URI: http://mlflow-server:5000
[2025-04-11T09:41:40.391+0000] {subprocess.py:106} INFO - --- Starting Final Model Training ---
[2025-04-11T09:41:40.392+0000] {subprocess.py:106} INFO - --- MLflow Run Started for Final Training ---
[2025-04-11T09:41:40.398+0000] {subprocess.py:106} INFO - Epoch [1/5], Train Loss: 0.4103, Test Loss: 0.3463
[2025-04-11T09:41:40.402+0000] {subprocess.py:106} INFO - Epoch [2/5], Train Loss: 0.0793, Test Loss: 0.4152
[2025-04-11T09:41:40.406+0000] {subprocess.py:106} INFO - Epoch [3/5], Train Loss: 0.0784, Test Loss: 0.3581
[2025-04-11T09:41:40.411+0000] {subprocess.py:106} INFO - Epoch [4/5], Train Loss: 0.0846, Test Loss: 0.3517
[2025-04-11T09:41:40.414+0000] {subprocess.py:106} INFO - Epoch [5/5], Train Loss: 0.0736, Test Loss: 0.3573
[2025-04-11T09:41:40.417+0000] {subprocess.py:106} INFO - Loaded best model state_dict from training run.
[2025-04-11T09:41:40.418+0000] {subprocess.py:106} INFO - Final model metrics logged to MLflow.
[2025-04-11T09:41:40.418+0000] {subprocess.py:106} INFO - Logging PyTorch model to MLflow...
[2025-04-11T09:41:40.419+0000] {subprocess.py:106} INFO - üèÉ View run final_model_training at: http://mlflow-server:5000/#/experiments/617953971205239203/runs/347da5e15985456e9f4b01768574a28d
[2025-04-11T09:41:40.420+0000] {subprocess.py:106} INFO - üß™ View experiment at: http://mlflow-server:5000/#/experiments/617953971205239203
[2025-04-11T09:41:40.420+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-04-11T09:41:40.421+0000] {subprocess.py:106} INFO -   File "/opt/***/src/models/train_model.py", line 241, in <module>
[2025-04-11T09:41:40.423+0000] {subprocess.py:106} INFO -     run_training(args.config)
[2025-04-11T09:41:40.424+0000] {subprocess.py:106} INFO -   File "/opt/***/src/models/train_model.py", line 219, in run_training
[2025-04-11T09:41:40.424+0000] {subprocess.py:106} INFO -     final_model, final_metrics = train_final_model(
[2025-04-11T09:41:40.425+0000] {subprocess.py:106} INFO -                                  ^^^^^^^^^^^^^^^^^^
[2025-04-11T09:41:40.425+0000] {subprocess.py:106} INFO -   File "/opt/***/src/models/train_model.py", line 144, in train_final_model
[2025-04-11T09:41:40.426+0000] {subprocess.py:106} INFO -     mlflow.pytorch.log_model(model, "model") # Logs the model structure and state_dict
[2025-04-11T09:41:40.427+0000] {subprocess.py:106} INFO -     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-11T09:41:40.427+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.11/site-packages/mlflow/pytorch/__init__.py", line 296, in log_model
[2025-04-11T09:41:40.428+0000] {subprocess.py:106} INFO -     return Model.log(
[2025-04-11T09:41:40.428+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^
[2025-04-11T09:41:40.429+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.11/site-packages/mlflow/models/model.py", line 932, in log
[2025-04-11T09:41:40.429+0000] {subprocess.py:106} INFO -     mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path, run_id)
[2025-04-11T09:41:40.429+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.11/site-packages/mlflow/tracking/fluent.py", line 1219, in log_artifacts
[2025-04-11T09:41:40.430+0000] {subprocess.py:106} INFO -     MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
[2025-04-11T09:41:40.430+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.11/site-packages/mlflow/tracking/client.py", line 2423, in log_artifacts
[2025-04-11T09:41:40.431+0000] {subprocess.py:106} INFO -     self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
[2025-04-11T09:41:40.431+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.11/site-packages/mlflow/tracking/_tracking_service/client.py", line 959, in log_artifacts
[2025-04-11T09:41:40.432+0000] {subprocess.py:106} INFO -     self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
[2025-04-11T09:41:40.434+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.11/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 66, in log_artifacts
[2025-04-11T09:41:40.439+0000] {subprocess.py:106} INFO -     mkdir(artifact_dir)
[2025-04-11T09:41:40.441+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.11/site-packages/mlflow/utils/file_utils.py", line 211, in mkdir
[2025-04-11T09:41:40.442+0000] {subprocess.py:106} INFO -     raise e
[2025-04-11T09:41:40.443+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.11/site-packages/mlflow/utils/file_utils.py", line 208, in mkdir
[2025-04-11T09:41:40.444+0000] {subprocess.py:106} INFO -     os.makedirs(target, exist_ok=True)
[2025-04-11T09:41:40.444+0000] {subprocess.py:106} INFO -   File "<frozen os>", line 215, in makedirs
[2025-04-11T09:41:40.445+0000] {subprocess.py:106} INFO -   File "<frozen os>", line 215, in makedirs
[2025-04-11T09:41:40.445+0000] {subprocess.py:106} INFO -   File "<frozen os>", line 215, in makedirs
[2025-04-11T09:41:40.445+0000] {subprocess.py:106} INFO -   [Previous line repeated 2 more times]
[2025-04-11T09:41:40.446+0000] {subprocess.py:106} INFO -   File "<frozen os>", line 225, in makedirs
[2025-04-11T09:41:40.446+0000] {subprocess.py:106} INFO - PermissionError: [Errno 13] Permission denied: '/mlruns'
[2025-04-11T09:41:41.398+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-04-11T09:41:41.413+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-11T09:41:41.421+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=lstm_stock_prediction_refactored, task_id=train_final_model, run_id=manual__2025-04-11T09:38:46.502188+00:00, execution_date=20250411T093846, start_date=20250411T094125, end_date=20250411T094141
[2025-04-11T09:41:41.442+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-11T09:41:41.446+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 66 for task train_final_model (Bash command failed. The command returned a non-zero exit code 1.; 457)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-11T09:41:41.475+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-11T09:41:41.485+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-11T09:41:41.488+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
